trigger:
  branches:
    include:
      - main  # Change this to your main branch name
  paths:
    exclude:
      - README.md  # Update with files that should not trigger a build

pr:
  branches:
    include:
      - '*'  # Trigger for all branches created from the main branch

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: TerraformInstaller@0
  inputs:
    terraformVersion: 'latest'  # Replace with a specific version if needed
    terraformLocation: 'Auto'

- task: TerraformCLI@0
  displayName: 'terraform init'
  inputs:
    providerServiceAws: 'AWSDevServiceConnection'
    providerAwsRegion: 'ap-southeast-1'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    command: 'init'

- task: TerraformCLI@0
  displayName: 'terraform validate'
  inputs:
    providerServiceAws: 'AWSDevServiceConnection'
    providerAwsRegion: 'ap-southeast-1'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    command: 'validate'

- task: TerraformCLI@0
  displayName: 'terraform apply'
  inputs:
    providerServiceAws: 'AWSDevServiceConnection'
    providerAwsRegion: 'ap-southeast-1'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    command: 'plan'
    commandOptions: '-out=tfplan -input=false'
    publishPlanResults: 'tfplan'
