trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - README.md

pr:
  branches:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: TerraformTaskV2@2
    inputs:
      provider: 'aws'
      command: 'init'
      workingDirectory: '$(System.DefaultWorkingDirectory)'
  
  - task: TerraformTaskV2@2
    inputs:
      provider: 'aws'
      command: 'validate'
      workingDirectory: '$(System.DefaultWorkingDirectory)'
  
  - task: TerraformTaskV2@2
    inputs:
      provider: 'aws'
      command: 'plan'
      commandOptions: '-out=tfplan -input=false'
      workingDirectory: '$(System.DefaultWorkingDirectory)'